### ISSUE TITLE
Initialization with Multiple App Ids 

### ISSUE THREAD

**Issue by mish-tan** [RusticiSoftware/scormcloud-api-v2-client-net#22]
Hi all, 

Similar question to: https://github.com/RusticiSoftware/scormcloud-api-v2-client-net/issues/6

Previously when we were using https://github.com/RusticiSoftware/SCORMCloud_NetLibrary, to deal with multiple app ids it was recommended we new up the Configuration to pass to a new instance of ScormEngineService every time. 

```
Configuration cfg =
    new RusticiSoftware.HostedEngine.Client.Configuration(
        "https://cloud.scorm.com/EngineWebServices",
        "your app id",
        "your secret key",
        "your origin string");

ScormEngineService service = new ScormEngineService(cfg);
```

Is the guidance on dealing with Multiple App Ids still the same? That is, newing up a Configuration class every time and passing that to a new instance of CourseApi? 
I get that we can now configure the values at startup but given we have multiple app Ids if I want to configure it with every new request to our service, what's the best practice / recommendations for this?  

Thanks for your time hopefully my question is clear.

**Comment by mjschuetze102** [comment]
This would be similar to how you would set up OAuth for a request. There is sample code in the README, albeit slightly hidden due to trying to keep the sample short. The relevant lines are [here](https://github.com/RusticiSoftware/scormcloud-api-v2-client-net/blob/54eba1bc5ef66634448ab0e8cfaa229185a9cd82/README.md?plain=1#L199-L221)

The sample in the comments would need to be slightly modified, but would look something similar to:
```
var courseApi = new CourseApi
{
    Configuration = new Configuration
    {
        Username = APP_ID,
        Password = SECRET_KEY
    }
};
```

> Is the guidance on dealing with Multiple App Ids still the same? That is, newing up a Configuration class every time and passing that to a new instance of CourseApi?

Yep. Using multiple App Ids will still require the use of creating a new configuration class for each

> I get that we can now configure the values at startup but given we have multiple app Ids if I want to configure it with every new request to our service, what's the best practice / recommendations for this?

If you are working with multiple App Ids, maybe having some sort of Map between an App Id and the `Configuration` class would work nicely. Ex: 

```
var config = new Configuration
{
    Username = APP_ID,
    Password = SECRET_KEY
};
var configs = new Dictionary<string, Configuration>() { { APP_ID, config } };

var courseApi = new CourseApi
{
    Configuration = configs[APP_ID]
};
```

I didn't test the above in a multi-threaded environment, so I don't know whether or not race conditions would end up in your code base if you were to use this exact block of code. The important bit is that a configuration with the App Id you want is passed into the constructor of the `CourseApi` class

**Comment by mjschuetze102** [comment]
I'm going to go ahead and close this ticket. Let me know if you have any other questions

**Comment by mish-tan** [comment]
Sorry I never got back to you, thank you so much for your advice and help with this! Really appreciated the sample code, managed to make it work for our scenario! 🙇‍♀️

**Comment by mjschuetze102** [comment]
🥳 Happy to hear it. Feel free to reach back out if you have any other questions
