### ISSUE TITLE
ParameterToFile throwing System.OutOfMemoryException 

### ISSUE THREAD

**Issue by mish-tan** [RusticiSoftware/scormcloud-api-v2-client-net#23]
Hi all, 

We are having an issue where attempts to upload a 300mb Scorm File via `CreateUploadAndImportCourseJob` is resulting in an `OutOfMemoryException`. We don't want to increase the available memory to 4gb, would it be possible for you to update this library so that it doesn't use so much memory handling large files? Do you have any recommendations on what we should do? Below is the results of our investigation...

Below is a screenshot of the exception call stack 
![image](https://user-images.githubusercontent.com/20408713/211986857-8ee7bb7a-1840-4e1f-909e-3f9e6e602de1.png)

Previously when we were using the V1 package, we did not have this issue, however when we upgraded to the V2 package it started happening. 

Testing Locally everything is ok because my computer has enough memory and I don't have restrictions on Visual Studio's usage of it (you can see in this screenshot the Process Memory is climbing to nearly 4gb), but in production the available memory has a limit of 1gb, so we're getting the exception... 
![image](https://user-images.githubusercontent.com/20408713/211987328-ea272c7b-c3ba-4b9e-929b-e576fab4045a.png)

Looking at the implementation of ParameterToFile, 

```
        public FileParameter ParameterToFile(string name, Stream stream)
        {
            if (stream is FileStream)
                return FileParameter.Create(name, ReadAsBytes(stream), Path.GetFileName(((FileStream)stream).Name));
            else
                return FileParameter.Create(name, ReadAsBytes(stream), "no_file_name_provided");
        }
```

currently seems that this implementation of Create is being used, `public static FileParameter Create(string name, byte[] data, string filename, string? contentType = null, FileParameterOptions? options = null)`, if this other overload is used `public static FileParameter Create(string name, Func<Stream> getFile, string fileName, string? contentType = null, FileParameterOptions? options = null)` it might be less memory intensive? 

Thanks for your time, hopefully I've included all the relevant information and it's clear! Please reach out if any confusion
Cheers! 

Tagging @raymondht and @chezka-arevalo cause they are also following this 🙏

**Comment by mjschuetze102** [comment]
Hello!

Thank you for digging into all of this. It does indeed seem that there are improvements that could be made here. Unfortunately I don't have a time frame for you on when that could be fixed. We have a fairly busy development schedule for the next month. This may be able to squeak in there somewhere, but I can't give a definite answer.

In the meantime, if you have the capability to host the courses you could import them into Cloud using "fetch" instead of "upload". What I mean by that...

You are currently using the CreateUploadAndImportCourseJob method which provides the file at the time the request is made. [CreateFetchAndImportCourseJob](https://cloud.scorm.com/docs/v2/reference/swagger/#/course/CreateFetchAndImportCourseJob) will start the import job where the first step is to download the file from a publicly accessible URL. Both of those methods will end up following the same code path on our servers, it's just a matter of how we get the file.

This may or may not be applicable given the constraints your system has, I was just trying to give an alternative while you wait for an update to this library.

Hopefully that helps, sorry I can't give you a more refined answer than that at the moment.

**Comment by mjschuetze102** [comment]
Another option I just thought of... You could fork this repo, make the changes locally, and then run with your custom build until this problem is fixed

**Comment by raymondht** [comment]
@mjschuetze102 thanks for your recommendation. Please do let us know when this issue is looked into by your team. Looking forward to hearing from you.

**Comment by mjschuetze102** [comment]
Hello all,

We've gone through and fixed the swagger template files to use the other overload as suggested. I'll be regenerating the client shortly and putting it up on NuGet after we run the last couple rounds of tests.

Thank you for your patience on this. Hopefully this fixes the problems you were seeing.

**Comment by mjschuetze102** [comment]
[Version 3.0.1](https://www.nuget.org/packages/Com.RusticiSoftware.Cloud.V2) has been released. Let me know if that fixes the problems you were seeing.

**Comment by raymondht** [comment]
Hi @mjschuetze102 and team,

We have upgraded the package and our app is no longer having the intense memory utilisation issue. Thanks for looking into this!

**Comment by mjschuetze102** [comment]
Glad to hear it. Let us know if you run into any more issues.
